config/routes.rb
require 'override_csp'

Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: '/graphiql', graphql_path: '/graphql'
  end

  direct :rails_public_blob do |blob|
    if Rails.env.development? || Rails.env.test? || ENV['CLOUDFRONT_HOST'].blank?
      route =
        if blob.is_a?(ActiveStorage::Variant) || blob.is_a?(ActiveStorage::VariantWithRecord)
          :rails_representation
        else
          :rails_blob
        end
      route_for(route, blob, only_path: true)
    else
      Cloudfront::GenerateSignedUrlService.new(blob).generate_url
    end
  end

  post '/graphql', to: 'graphql#execute'

  devise_for :users, only: %i[sessions omniauth_callbacks], controllers: { sessions: 'users/sessions', omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_scope :user do
    post 'users/send_reset_password_email', controller: 'users/sessions', action: 'send_reset_password_email', as: 'user_send_reset_password_email'
    get 'users/token', controller: 'users/sessions', action: 'token', as: 'user_token'
    get 'users/auth_callback', controller: 'users/sessions', action: 'auth_callback', as: 'user_auth_callback'
    get 'users/reset_password', controller: 'users/sessions', action: 'reset_password', as: 'reset_password'
    post 'users/update_password', controller: 'users/sessions', action: 'update_password', as: 'update_password'
    get 'users/sign_in_with_email', controller: 'users/sessions', action: 'sign_in_with_email', as: 'sign_in_with_email'
    get 'users/request_password_reset', controller: 'users/sessions', action: 'request_password_reset', as: 'request_password_reset'

    if Rails.env.development?
      get 'users/auth/developer', controller: 'users/omniauth_callbacks', action: 'passthru', as: 'user_developer_omniauth_authorize'
      post 'users/auth/developer/callback', controller: 'users/omniauth_callbacks', action: 'developer'
    end
  end

  get 'users/delete_account', controller: 'users', action: 'delete_account', as: 'delete_account'

  post 'users/email_bounce', controller: 'users/postmark_webhook', action: 'email_bounce'

  get 'users/update_email', controller: 'users', action: 'update_email', as: 'update_email'

  authenticate :user, ->(u) { AdminUser.where(email: u.email).present? } do
    mount Delayed::Web::Engine, at: '/jobs'
    mount OverrideCsp.new(Flipper::UI.app(Flipper)), at: '/toggle'
  end

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  resource :applicants, only: [] do
    get '/:token/enroll', action: 'enroll', as: 'enroll'
  end

  resources :notifications, only: %i[show]

  resource :school, only: [] do
    get 'customize'
    get 'admins'
    post 'images'
  end

  namespace :school, module: 'schools' do
    [
      '/',
      'courses',
      'courses/new',
      'courses/:course_id',
      'courses/:course_id/details',
      'courses/:course_id/images',
      'courses/:course_id/actions',
      'courses/:course_id/cohorts',
      'courses/:course_id/cohorts/new',
      'cohorts/:cohort_id/details',
      'cohorts/:cohort_id/actions',
      'courses/:course_id/students',
      'courses/:course_id/students/new',
      'courses/:course_id/students/import',
      'students/:student_id/details',
      'students/:student_id/actions',
      'courses/:course_id/teams',
      'courses/:course_id/teams/new',
      'teams/:team_id/details',
      'teams/:team_id/actions',
    ].each do |path|
      get path, action: 'school_router'
    end

    resources :faculty, only: %i[create update destroy], as: 'coaches', path: 'coaches' do
      collection do
        get '/', action: 'school_index'
      end
    end

    resources :calendars, only: %i[update], controller: 'calendars'
    resources :calendar_events, only: %i[update destroy], controller: 'calendar_events'

    resources :targets, only: [] do
      resource :content_block, only: %i[create]
      member do
        get 'action', action: 'action'
        patch 'update_action', action: 'update_action'
      end
    end

    resources :cohorts, only: [] do
      member do
        post 'bulk_import_students'
      end
    end

    resources :assignments, only: [] do
      member do
        patch :update_milestone_number
      end
    end

    resources :courses, only: [] do
      member do
        get 'applicants'
        get 'calendar_events'
        get 'curriculum'
        get 'exports'
        get 'authors'
        get 'certificates'
        post 'certificates', action: 'create_certificate'
        get 'evaluation_criteria'
        post 'attach_images'
        get 'calendar_month_data'
        get 'assignments'
      end

      resources :calendar_events, only: %i[new create show edit], controller: 'calendar_events'

      resources :calendars, only: %i[new create edit], controller: 'calendars'

      resources :authors, only: %w[show new]

      resources :applicants, only: :show do
        member do
          get 'actions', action: :show
          get 'details', action: :show
        end
      end

      resources :targets, only: [] do
        member do
          get 'content'
          get 'details'
          get 'versions'
        end
      end

      resources :levels, only: %i[create]

      resources :faculty, as: 'coaches', path: 'coaches', only: [] do
        collection do
          get '/', action: 'course_index'
        end
      end

      get 'students'
      post 'delete_coach_enrollment'
      post 'update_coach_enrollments'
    end

    resources :students, as: 'students', path: 'students', except: %i[index] do
      collection do
        post 'team_up'
      end
    end

    resources :levels, only: %i[update] do
      resources :target_groups, only: %i[create]
    end

    resources :target_groups, only: %i[update]

    resources :communities, only: %i[index]
  end

  resources :organisations, only: %i[show index] do
    resources :cohorts, module: 'organisations', only: %i[show] do
      member do
        get 'students'
      end
    end

    resources :courses,  module: 'organisations', only: [] do
      member do
        get 'active_cohorts'
        get 'ended_cohorts'
      end
    end
  end

  namespace :org, module: 'organisations' do
    resources :students, only: %[show] do
      member do
        get 'submissions'
      end
    end
  end

  resources :communities, only: %i[show] do
    member do
      get 'new_topic'
      get ':name', action: 'show'
    end
  end

  get 'topics/:id(/:title)', controller: 'topics', action: 'show', as: 'topic'

  get 'posts/:id/versions', controller: 'posts', action: 'versions', as: 'post_version'

  get 'dashboard', controller: 'users', action: 'dashboard', as: 'dashboard'

  resource :user, only: %i[edit] do
    post 'upload_avatar'
    post 'clear_discord_id'
    get 'discord_account_required'
  end

  resources :timeline_event_files, only: %i[create] do
    member do
      get 'download'
    end
  end

  scope 'coaches', controller: 'faculty' do
    get '/', action: 'index', as: 'coaches_index'
  end

  # Student show
  scope 'students', controller: 'students' do
    get '/:id/report', action: 'report', as: 'student_report'
  end

  get 'styleguide', to: 'home#styleguide', constraints: DevelopmentConstraint.new

  get 'manifest', to: 'home#manifest'
  get 'offline', to: 'home#offline'
  root 'home#index'

  get 'agreements/:agreement_type', as: 'agreement', controller: 'home', action: 'agreement'

  resources :targets, only: %i[show] do
    member do
      get 'details_v2'
      get ':slug', action: 'show'
    end
  end

  resources :timeline_events, only: %i[show], path: 'submissions' do
    member do
      get 'review', action: 'review'
    end
  end

  resources :courses, only: %i[show] do
    member do
      get 'review', action: 'review'
      get 'cohorts', action: 'cohorts'
      get 'calendar', action: 'calendar'
      get 'calendar_month_data', action: 'calendar_month_data'
      get 'leaderboard', action: 'leaderboard'
      get 'curriculum', action: 'curriculum'
      get 'report', action: 'report'
      get 'apply', action: 'apply'
      post 'apply', action: 'process_application'
      get '/(:name)', action: 'show'
    end
  end

  resources :cohorts, only: %i[show] do
    member do
      get 'students', action: 'students'
    end
  end

  resources :markdown_attachments, only: %i[create] do
    member do
      get '/:token', action: 'download', as: 'download'
    end
  end

  get '/c/:serial_number', to: 'issued_certificates#verify', as: :issued_certificate
  get '/help/:document', to: 'help#show'
  get '/oauth/:provider', to: 'home#oauth', as: 'oauth', constraints: SsoConstraint.new
  get '/oauth_error', to: 'home#oauth_error', as: 'oauth_error'

  # Allow developers to simulate the error pages.
  get '/errors/:error_type', to: 'errors#simulate', constraints: DevelopmentConstraint.new

  get '/service-worker.js', to: 'home#service_worker'
  get '/favicon.ico', to: 'home#favicon'
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  include RecaptchaVerifiable
  include DiscordAccountRequirable

  before_action :authenticate_user!,
                except: %i[show apply process_application curriculum]

  before_action :preview_or_authenticate, only: %i[curriculum]
  before_action :require_discord_account, only: %i[curriculum report]

  # GET /courses/:id/curriculum
  def curriculum
    @presenter = Courses::CurriculumPresenter.new(view_context, @course)
    render layout: "student_course"
  end

  # GET /courses/:id/leaderboard?weeks_before=
  def leaderboard
    @course = authorize(find_course)
    @on = params[:on]
    render layout: "student_course"
  end

  # GET /courses/:id/apply
  def apply
    @course = authorize(find_course)
    @show_checkbox_recaptcha = params[:visible_recaptcha].present?

    save_tag
  end

  # POST /courses/:id/apply
  def process_application
    @course = authorize(find_course)

    form = Courses::EnrollmentForm.new(@course)

    recaptcha_success =
      recaptcha_success?(@form, action: "public_course_enrollment")

    unless recaptcha_success
      redirect_to apply_course_path(params[:id], visible_recaptcha: 1)
      return
    end

    if form.validate(params)
      form.create_applicant(session)

      flash[:success] = t(".sent_mail")

      redirect_to root_path
    else
      flash[:error] = t(
        ".errors",
        form_errors: form.errors.full_messages.join(", ")
      )

      redirect_to apply_course_path(params[:id], visible_recaptcha: 1)
    end
  end

  # GET /courses/:id/(:slug)
  def show
    @course = authorize(find_course)
    render layout: "student"
  end

  # GET /courses/:id/review
  def review
    @course = authorize(find_course)
    render html: "", layout: "app_router"
  end

  # GET /courses/:id/cohorts
  def cohorts
    @course = authorize(find_course)
    render layout: "student_course"
  end

  # GET /courses/:id/report
  def report
    @course = authorize(find_course)
    @presenter = Courses::ReportPresenter.new(view_context, @course, student)
    render layout: "student_course"
  end

  # GET /courses/:id/calendar
  def calendar
    @course = authorize(find_course)
    @presenter = Courses::CalendarsPresenter.new(view_context, @course, params)
    render layout: "student_course"
  end

  def calendar_month_data
    @course = authorize(find_course)
    @presenter = Courses::CalendarsPresenter.new(view_context, @course, params)
    render json: @presenter.month_data
  end

  private

  def course
    @course ||= Course.find(params[:id])
  end

  def preview_or_authenticate
    course = find_course

    authenticate_user! unless course.public_preview?

    @course = authorize(course)
  end

  def student
    @student ||=
      @course.students.not_dropped_out.find_by(user_id: current_user.id)
  end

  def find_course
    policy_scope(Course).find(params[:id])
  end

  def save_tag
    return if params[:tag].blank?

    if params[:tag].in?(current_school.student_tag_list)
      session[:applicant_tag] = params[:tag]
    end
  end
end

app/controllers/organisations/courses_controller.rb
module Organisations
  class CoursesController < ApplicationController
    before_action :authenticate_user!
    before_action :find_organisation_and_course,
                  only: %i[active_cohorts ended_cohorts]

    layout "student"

    def active_cohorts
      @active_cohorts = find_cohorts(:active)
    end

    def ended_cohorts
      @ended_cohorts = find_cohorts(:ended)
    end

    private

    def find_organisation_and_course
      @organisation = policy_scope(Organisation).find(params[:organisation_id])
      @course =
        authorize current_school.courses.find(params[:id]),
                  policy_class: Organisations::CoursePolicy
      @cohorts = @organisation.cohorts.where(course_id: @course.id).distinct
    end

    def find_cohorts(status)
      cohorts = status == :active ? @cohorts.active : @cohorts.ended
      paged_cohorts = cohorts.page(params["#{status}_cohort_page"]).per(10)
      if paged_cohorts.count.zero?
        paged_cohorts.page(paged_cohorts.total_pages).per(10)
      else
        paged_cohorts
      end
    end
  end
end

app/controllers/schools/applicants_controller.rb
module Schools
  class ApplicantsController < SchoolsController
    # GET /school/courses/:course_id/applicant/:id
    def show
      @course = current_school.courses.find(params[:course_id])
      @applicant =
        authorize(
          @course.applicants.find(params[:id]),
          policy_class: Schools::CourseApplicantPolicy
        )
      render 'schools/courses/applicants'
    end
  end
end

app/controllers/schools/assignments_controller.rb
module Schools
  class AssignmentsController < ApplicationController
    # PATCH /school/assignments/:id/update_milestone_number
    def update_milestone_number
      target =
        authorize(
          Target.find(params[:id]),
          policy_class: Schools::AssignmentPolicy
        )

      Schools::MilestoneSortService.new(target, params[:direction]).execute

      redirect_to assignments_school_course_path(
                    id: target.course.id,
                    page: (params[:page] || 1)
                  )
    end
  end
end

app/controllers/schools/authors_controller.rb
module Schools
  class AuthorsController < SchoolsController
    # GET /school/courses/:course_id/authors/:id
    def show
      @course = current_school.courses.find(params[:course_id])

      authorize(
        @course.course_authors.find(params[:id]),
        policy_class: Schools::CourseAuthorPolicy,
      )

      render "schools/courses/authors"
    end

    # GET /school/courses/:course_id/authors/new
    def new
      @course = current_school.courses.find(params[:course_id])

      authorize(
        @course.course_authors.new,
        policy_class: Schools::CourseAuthorPolicy,
      )

      render "schools/courses/authors"
    end
  end
end

app/controllers/schools/calendars_controller.rb
module Schools
  class CalendarsController < SchoolsController
    layout "school"

    # GET /school/courses/:course_id/calendars/new
    def new
      @course = current_school.courses.find(params[:course_id])
      @calendar = Calendar.new
      authorize(@calendar, policy_class: Schools::CalendarEventPolicy)
    end

    # GET /school/courses/:course_id/calendars/edit
    def edit
      @course = current_school.courses.find(params[:course_id])
      @calendar = @course.calendars.find(params[:id])
      authorize(@calendar, policy_class: Schools::CalendarEventPolicy)
    end

    # POST /school/courses/:course_id/calendars
    def create
      @course = current_school.courses.find(params[:course_id])
      calendar_params = params.require(:calendar).permit(:name, cohort_ids: [])

      calendar_params[:cohort_ids] = @course
        .cohorts
        .where(id: calendar_params[:cohort_ids])
        .pluck(:id)

      authorize(@course, policy_class: Schools::CalendarEventPolicy)
      @course.calendars.create!(calendar_params)

      flash[:success] = I18n.t("calendars.create.success")

      redirect_to school_course_calendar_events_path(@course)
    end

    # POST /school/calendars/:id
    def update
      @calendar = current_school.calendars.find(params[:id])
      @course = @calendar.course
      calendar_params = params.require(:calendar).permit(:name, cohort_ids: [])
      calendar_params[:cohort_ids] = @course
        .cohorts
        .where(id: calendar_params[:cohort_ids])
        .pluck(:id)
      @calendar.update!(calendar_params)

      authorize(@calendar, policy_class: Schools::CalendarEventPolicy)

      flash[:success] = I18n.t("calendars.update.success")
      redirect_to school_course_calendar_events_path(@course)
    end
  end
end

app/controllers/schools/cohorts_controller.rb
module Schools
  class CohortsController < SchoolsController
    include CamelizeKeys
    include StringifyIds

    # POST /school/cohorts/:id/bulk_import_students
    def bulk_import_students
      @cohort =
        authorize(scope.find(params[:id]), policy_class: Schools::CohortPolicy)

      form = ::Cohorts::BulkImportStudentsForm.new(@cohort)
      form.current_user = current_user

      props =
        if form.validate(params)
          form.save
          { success: true }
        else
          { error: form.errors.full_messages.join(', ') }
        end

      render json: camelize_keys(stringify_ids(props))
    end

    private

    def scope
      @scope ||=
        policy_scope(Cohort, policy_scope_class: Schools::CohortPolicy::Scope)
    end
  end
end

app/controllers/schools/communities_controller.rb
module Schools
  class CommunitiesController < SchoolsController
    def index
      @school = authorize(current_school, policy_class: Schools::CommunityPolicy)
      render layout: 'school'
    end
  end
end

app/views/schools/courses/_event_card.html.erb
<div class="overflow-hidden rounded-lg">
  <a
      href="<%=school_course_calendar_event_path(@course,event, calendar_id: params[:calendar_id])%>"
      class="<%="block p-4 bg-#{event.color}-50 hover:bg-#{event.color}-200 focus:bg-#{event.color}-100 transition focus:outline-none"%>"
      ariaLabel="eventName on eventDate at eventTime">
    <div class="flex justify-between">
      <div class="flex gap-3 items-start">
        <div class="<%="w-2 h-2 mt-2 rounded-full " + "bg-#{event.color}-500"%>"></div>
        <div>
          <p class="font-semibold text-base"><%= event.title %></p>
          <p class="font-medium text-sm">
            <%= event.display_time %>
          </p>
        </div>
      </div>
      <p class="text-black/50 text-xs"> <%= event.calendar.name %> </p>
    </div>
  </a>
  <% if event.link_url.present? %>
    <div>
      <a
          href="<%= event.link_url %>"
          aria-label="Link to event"
          target="_blank"
          rel="noopener noreferrer"
          class="<%="ps-9 pe-5  py-4 block text-primary-500 font-medium text-sm transition-all border-t border-black/5 hover:underline focus:underline focus:outline-none " + "bg-#{event.color}-50 hover:bg-#{event.color}-100 focus:bg-#{event.color}-100"%>">
        <div class="flex gap-2 items-center">
          <i class="if i-external-link-regular if-fw rtl:-rotate-90"></i>
          <p>
            <%= event.link_title.present? ? event.link_title : event.link_url %>
          </p>
        </div>
      </a>
    </div>
  <% end %>
</div>

app/views/schools/courses/applicants.html.erb
<% content_for(:head) do %>
  <title><%= @course.name %> | <%= t(".title") %> </title>
<% end %>
<script id="schools-courses-applicants__props" type="application/json">
  <%= Schools::Courses::ApplicantsPresenter.new(self, @course).props_to_json.html_safe %>
</script>

app/views/schools/courses/assignments.html.erb
<% content_for(:head) do %>
  <title><%= @course.name %> | <%= t(".title") %> </title>
<% end %>
<div class="relative" id="schoolrouter-innerpage-data">
  <div class="max-w-3xl mt-2 mx-auto mb-20">
    <div  class="flex justify-between items-center gap-5 py-8">
      <div class="w-3/4">
        <p class="text-xs text-gray-500 uppercase font-semibold"><%= t(".list_title") %></p>
        <h1 class="font-semibold text-2xl text-gray-600"><%= @course.name %></h1>
        <p class="text-sm text-gray-600 mt-1"><%= t(".milestone_msg")%></p>
      </div>
      <div class="px-3 md:px-4 py-2 bg-yellow-100 rounded-md border border-yellow-200 flex items-center flex-shrink-0 font-medium text-yellow-800">
        <i class="if i-milestone-solid if-fw text-2xl text-yellow-900" ></i>
        <span class="pointer-events-none">#</span>
      </div>
    </div>
    <div class="pb-10">
      <div class="rounded-lg border border-gray-300 shadow-md divide-y overflow-hidden">
        <% @milestones.each_with_index do |target, index| %>
          <div class="flex items-center target-group__target-container overflow-hidden relative hover:bg-gray-50 hover:text-primary-500">
            <% unless @milestones.size < 1 %>
              <div class="flex flex-col target-group__target-reorder relative h-full border-e border-transparent text-gray-600 justify-between items-center">
                <%= button_to update_milestone_number_school_assignment_path(target, direction: :up, page: @page_no),
                method: :patch, title:"Move up", class: "h-full", form_class: "flex items-center justify-center cursor-pointer w-9 h-9 p-1 text-gray-400 hover:bg-gray-50 focus:outline-none focus:text-primary-500 #{"invisible" unless index > 0 || !@milestones.first_page?}" do %>
                  <i class="if i-arrow-up-solid if-fw" ></i>
                <% end %>
                <%= button_to update_milestone_number_school_assignment_path(target, direction: :down, page: @page_no),
                method: :patch, title:"Move down",  class: "h-full", form_class: "flex items-center justify-center cursor-pointer w-9 h-9 p-1 text-gray-400 hover:bg-gray-50 focus:outline-none focus:text-primary-500 #{"invisible" unless index < @milestones.size - 1 || !@milestones.last_page?}" do %>
                  <i  class="if i-arrow-down-solid if-fw" ></i>
                <% end %>
              </div>
            <% end %>
            <%= link_to details_school_course_target_path(@course, target), class: "flex justify-between w-full items-center h-full py-5 px-4" do %>
              <p class="text-sm"><%= target.title %></p>
              <div class="flex items-center flex-shrink-0 text-xs font-medium bg-yellow-100 border border-yellow-200 text-yellow-800 ms-2 px-1.5 md:px-2 py-1 rounded-md">
                <i class="if i-milestone-solid if-fw" ></i>
                <span><%= target.milestone_number %></span>
              </div>
            <% end %>
          </div>
        <% end %>
        <% if @milestones.size < 1 %>
          <div class="flex justify-center">
            <p class="py-6 text-sm text-gray-400 font-medium"><%= t(".no_milestones") %> </p>
          </div>
        <% end %>
      </div>
    </div>
    <div class="bg-gray-50 border-t border-gray-300 p-5 fixed bottom-0 end-0 flex flex-col items-center" style="width: calc(100% - 19.5rem)">
      <%= paginate @milestones %>
      <div class="text-center text-sm mt-2">
        <%= page_entries_info @milestones, entry_name: 'Milestone' %>
      </div>
    </div>
  </div>
</div>

app/views/schools/courses/authors.html.erb
<% content_for(:head) do %>
  <title><%= @course.name %> | <%= t(".title") %> </title>
<% end %>
<script id="schools-courses-authors__props" type="application/json">
  <%= Schools::Courses::AuthorsPresenter.new(self, @course).props_to_json.html_safe %>
</script>

app/views/schools/courses/calendar_events.html.erb
<% content_for(:head) do %>
  <title><%= @course.name %> | <%= t(".title") %> </title>
<% end %>
<div class="relative" id="schoolrouter-innerpage-data">
  <% if @course.calendars.present? %>
    <div class="max-w-6xl mx-auto px-5 pb-6 mt-8">
      <div class="flex items-end justify-between gap-2">
        <h1 class="text-xl font-semibold"> <%= t(".calendar") %>  </h1>
        <div>
          <%= link_to new_school_course_calendar_event_path(@course, calendar_id: params[:calendar_id]), class: "btn btn-primary block" do %>
            <i class="if i-plus-regular if-fw" ></i>
            <%= t(".add_event_button") %>
          <% end %>
        </div>
      </div>
      <div class="mt-4 grid grid-cols-12 bg-gray-50 rounded-lg border border-gray-200 relative">
        <div class="col-span-4 p-6 border-e border-gray-200">
          <div class="sticky top-4">
            <div id="course-calendar-picker" class="pb-4 " >
              <div data-re-component="CalendarsIndex__DatePicker" data-re-json=<%=@presenter.date_picker_props%>></div>
            </div>
            <div class="pt-6 border-t border-gray-200 flex items-center justify-between gap-2 p-1">
              <p class="text-lg font-semibold "><%= t(".calendars") %> </p>
              <a
                class="block btn btn-default btn-small"
                href="<%= new_school_course_calendar_path(@course, calendar_id: params[:calendar_id])%>">
                <i class="if i-plus-regular if-fw" ></i>
                <span><%= t(".add_calendar_button") %> </span>
              </a>
            </div>
            <% @course.calendars.each do |calendar|  %>
              <div class="bg-white mt-2 px-2 py-1 rounded-md text-sm flex items-center justify-between">
                <span class="flex items-center gap-2 font-medium">
                  <%= calendar.name %>
                </span>
                <a href="<%= edit_school_course_calendar_path(@course, calendar) %>" class="bg-gray-50 p-2 rounded-md hover:bg-gray-200 hover:text-primary-500 focus:ring-2 focus:ring-focusColor-500 transition">
                  <i class="if i-edit-regular if-fw text-base" ></i>
                </a>
              </div>
            <% end %>
          </div>
        </div>
        <div class="col-span-8 bg-white flex-1 rounded-e-lg">
          <div class="flex gap-4 items-center justify-between bg-gray-50 rounded-tr-lg p-6">
            <p class="text-lg font-semibold"><%= t(".events") %></p>
            <div class="flex items-center gap-2">
              <label class="text-sm font-medium flex-shrink-0 text-gray-600"><%= t(".calendar_filter_label") %></label>
              <div data-re-component="SelectLink" data-re-json="<%= @presenter.calendar_link_props.to_json %>"></div>
            </div>
          </div>
          <div class="flex flex-col gap-8 divide-y p-6">
            <div>
              <div>
                <p class="font-semibold text-sm text-gray-600">
                  <%= @presenter.selected_date %>
                  <% if @presenter.today? %>
                    <span aria-hidden="true">-</span>
                    <em class="font-normal"><%= t(".today") %></em>
                  <% end %>
                </p>
                <% if @presenter.events_for_day.blank? %>
                  <div class="mt-3 flex flex-col items-center text-center p-4 bg-gray-100 rounded-lg">
                    <i class="if i-calendar-solid if-fw text-3xl"></i>
                    <p class="text-sm font-semibold mt-4"><%= t(".empty_events") %></p>
                  </div>
                <% end %>
              </div>
              <div>
                <div class="mt-3 flex flex-col gap-4">
                  <% @presenter.events_for_day.each do |event|%>
                    <%= render partial: "event_card", locals: {event: event} %>
                  <% end %>
                </div>
              </div>
            </div>
            <% if @presenter.upcoming_events_for_month.present? %>
              <div class="pt-4">
                <p class="font-semibold text-sm text-gray-600"> <%= t(".upcoming_events_in") + " " + @presenter.selected_month %></p>
                <div>
                  <div class="mt-3 flex flex-col gap-4">
                    <% @presenter.upcoming_events_for_month.each do |event|%>
                      <%= render partial: "event_card", locals: {event: event} %>
                    <% end %>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% else %>
    <div class="max-w-6xl mx-auto px-5 pb-6 mt-8">
      <div class="bg-gray-50 p-12 flex flex-col items-center justify-center rounded-lg ">
        <div class="w-64">
          <%= image_tag 'shared/no-calendar-icon.svg', class: 'w-full', alt: 'Internal server error' %>
        </div>
        <h2 class="font-semibold mt-3"><%= t(".no_calendars_message") %></h2>
        <p class="text-sm"><%= t(".no_calendars_sub_text") %></p>
        <a
          class="block btn btn-primary mt-4"
          href=<%= new_school_course_calendar_path(@course)%>>
          <i class="if i-plus-regular if-fw" ></i>
          <span><%= t(".add_calendar_button") %> </span>
        </a>
      </div>
    </div>
  <% end %>
</div>

app/views/schools/courses/certificates.html.erb
<% presenter = Schools::Courses::CertificatesPresenter.new(self, @course) %>
<% content_for(:head) do %>
  <title><%= @course.name %> | <%= t(".title") %> </title>
<% end %>
<script id="schools-courses-certificates__props" type="application/json">
  <%= presenter.props_to_json.html_safe %>
</script>