config/routes.rb
require 'override_csp'

Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: '/graphiql', graphql_path: '/graphql'
  end

  direct :rails_public_blob do |blob|
    if Rails.env.development? || Rails.env.test? || ENV['CLOUDFRONT_HOST'].blank?
      route =
        if blob.is_a?(ActiveStorage::Variant) || blob.is_a?(ActiveStorage::VariantWithRecord)
          :rails_representation
        else
          :rails_blob
        end
      route_for(route, blob, only_path: true)
    else
      Cloudfront::GenerateSignedUrlService.new(blob).generate_url
    end
  end

  post '/graphql', to: 'graphql#execute'

  devise_for :users, only: %i[sessions omniauth_callbacks], controllers: { sessions: 'users/sessions', omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_scope :user do
    post 'users/send_reset_password_email', controller: 'users/sessions', action: 'send_reset_password_email', as: 'user_send_reset_password_email'
    get 'users/token', controller: 'users/sessions', action: 'token', as: 'user_token'
    get 'users/auth_callback', controller: 'users/sessions', action: 'auth_callback', as: 'user_auth_callback'
    get 'users/reset_password', controller: 'users/sessions', action: 'reset_password', as: 'reset_password'
    post 'users/update_password', controller: 'users/sessions', action: 'update_password', as: 'update_password'
    get 'users/sign_in_with_email', controller: 'users/sessions', action: 'sign_in_with_email', as: 'sign_in_with_email'
    get 'users/request_password_reset', controller: 'users/sessions', action: 'request_password_reset', as: 'request_password_reset'

    if Rails.env.development?
      get 'users/auth/developer', controller: 'users/omniauth_callbacks', action: 'passthru', as: 'user_developer_omniauth_authorize'
      post 'users/auth/developer/callback', controller: 'users/omniauth_callbacks', action: 'developer'
    end
  end

  get 'users/delete_account', controller: 'users', action: 'delete_account', as: 'delete_account'

  post 'users/email_bounce', controller: 'users/postmark_webhook', action: 'email_bounce'

  get 'users/update_email', controller: 'users', action: 'update_email', as: 'update_email'

  authenticate :user, ->(u) { AdminUser.where(email: u.email).present? } do
    mount Delayed::Web::Engine, at: '/jobs'
    mount OverrideCsp.new(Flipper::UI.app(Flipper)), at: '/toggle'
  end

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  resource :applicants, only: [] do
    get '/:token/enroll', action: 'enroll', as: 'enroll'
  end

  resources :notifications, only: %i[show]

  resource :school, only: [] do
    get 'customize'
    get 'admins'
    post 'images'
  end

  namespace :school, module: 'schools' do
    [
      '/',
      'courses',
      'courses/new',
      'courses/:course_id',
      'courses/:course_id/details',
      'courses/:course_id/images',
      'courses/:course_id/actions',
      'courses/:course_id/cohorts',
      'courses/:course_id/cohorts/new',
      'cohorts/:cohort_id/details',
      'cohorts/:cohort_id/actions',
      'courses/:course_id/students',
      'courses/:course_id/students/new',
      'courses/:course_id/students/import',
      'students/:student_id/details',
      'students/:student_id/actions',
      'courses/:course_id/teams',
      'courses/:course_id/teams/new',
      'teams/:team_id/details',
      'teams/:team_id/actions',
    ].each do |path|
      get path, action: 'school_router'
    end

    resources :faculty, only: %i[create update destroy], as: 'coaches', path: 'coaches' do
      collection do
        get '/', action: 'school_index'
      end
    end

    resources :calendars, only: %i[update], controller: 'calendars'
    resources :calendar_events, only: %i[update destroy], controller: 'calendar_events'

    resources :targets, only: [] do
      resource :content_block, only: %i[create]
      member do
        get 'action', action: 'action'
        patch 'update_action', action: 'update_action'
      end
    end

    resources :cohorts, only: [] do
      member do
        post 'bulk_import_students'
      end
    end

    resources :assignments, only: [] do
      member do
        patch :update_milestone_number
      end
    end

    resources :courses, only: [] do
      member do
        get 'applicants'
        get 'calendar_events'
        get 'curriculum'
        get 'exports'
        get 'authors'
        get 'certificates'
        post 'certificates', action: 'create_certificate'
        get 'evaluation_criteria'
        post 'attach_images'
        get 'calendar_month_data'
        get 'assignments'
      end

      resources :calendar_events, only: %i[new create show edit], controller: 'calendar_events'

      resources :calendars, only: %i[new create edit], controller: 'calendars'

      resources :authors, only: %w[show new]

      resources :applicants, only: :show do
        member do
          get 'actions', action: :show
          get 'details', action: :show
        end
      end

      resources :targets, only: [] do
        member do
          get 'content'
          get 'details'
          get 'versions'
        end
      end

      resources :levels, only: %i[create]

      resources :faculty, as: 'coaches', path: 'coaches', only: [] do
        collection do
          get '/', action: 'course_index'
        end
      end

      get 'students'
      post 'delete_coach_enrollment'
      post 'update_coach_enrollments'
    end

    resources :students, as: 'students', path: 'students', except: %i[index] do
      collection do
        post 'team_up'
      end
    end

    resources :levels, only: %i[update] do
      resources :target_groups, only: %i[create]
    end

    resources :target_groups, only: %i[update]

    resources :communities, only: %i[index]
  end

  resources :organisations, only: %i[show index] do
    resources :cohorts, module: 'organisations', only: %i[show] do
      member do
        get 'students'
      end
    end

    resources :courses,  module: 'organisations', only: [] do
      member do
        get 'active_cohorts'
        get 'ended_cohorts'
      end
    end
  end

  namespace :org, module: 'organisations' do
    resources :students, only: %[show] do
      member do
        get 'submissions'
      end
    end
  end

  resources :communities, only: %i[show] do
    member do
      get 'new_topic'
      get ':name', action: 'show'
    end
  end

  get 'topics/:id(/:title)', controller: 'topics', action: 'show', as: 'topic'

  get 'posts/:id/versions', controller: 'posts', action: 'versions', as: 'post_version'

  get 'dashboard', controller: 'users', action: 'dashboard', as: 'dashboard'

  resource :user, only: %i[edit] do
    post 'upload_avatar'
    post 'clear_discord_id'
    get 'discord_account_required'
  end

  resources :timeline_event_files, only: %i[create] do
    member do
      get 'download'
    end
  end

  scope 'coaches', controller: 'faculty' do
    get '/', action: 'index', as: 'coaches_index'
  end

  # Student show
  scope 'students', controller: 'students' do
    get '/:id/report', action: 'report', as: 'student_report'
  end

  get 'styleguide', to: 'home#styleguide', constraints: DevelopmentConstraint.new

  get 'manifest', to: 'home#manifest'
  get 'offline', to: 'home#offline'
  root 'home#index'

  get 'agreements/:agreement_type', as: 'agreement', controller: 'home', action: 'agreement'

  resources :targets, only: %i[show] do
    member do
      get 'details_v2'
      get ':slug', action: 'show'
    end
  end

  resources :timeline_events, only: %i[show], path: 'submissions' do
    member do
      get 'review', action: 'review'
    end
  end

  resources :courses, only: %i[show] do
    member do
      get 'review', action: 'review'
      get 'cohorts', action: 'cohorts'
      get 'calendar', action: 'calendar'
      get 'calendar_month_data', action: 'calendar_month_data'
      get 'leaderboard', action: 'leaderboard'
      get 'curriculum', action: 'curriculum'
      get 'report', action: 'report'
      get 'apply', action: 'apply'
      post 'apply', action: 'process_application'
      get '/(:name)', action: 'show'
    end
  end

  resources :cohorts, only: %i[show] do
    member do
      get 'students', action: 'students'
    end
  end

  resources :markdown_attachments, only: %i[create] do
    member do
      get '/:token', action: 'download', as: 'download'
    end
  end

  get '/c/:serial_number', to: 'issued_certificates#verify', as: :issued_certificate
  get '/help/:document', to: 'help#show'
  get '/oauth/:provider', to: 'home#oauth', as: 'oauth', constraints: SsoConstraint.new
  get '/oauth_error', to: 'home#oauth_error', as: 'oauth_error'

  # Allow developers to simulate the error pages.
  get '/errors/:error_type', to: 'errors#simulate', constraints: DevelopmentConstraint.new

  get '/service-worker.js', to: 'home#service_worker'
  get '/favicon.ico', to: 'home#favicon'
end

app/models/timeline_event.rb
# frozen_string_literal: true

# JSON fields schema:
#
# checklist: [
#   {
#     kind: string - should match the target checklist kind (shortText, longText, link, files, multiChoice)
#     title: string - title from the target checklist
#     result: string - answer for the question taken from the user
#     status: string - should be one of noAnswer, Passed, Failed.
#   },
#   ...
# ]

class TimelineEvent < ApplicationRecord
  belongs_to :target
  belongs_to :evaluator, class_name: "Faculty", optional: true
  belongs_to :reviewer, class_name: "Faculty", optional: true

  has_many :target_evaluation_criteria, through: :target
  has_many :evaluation_criteria, through: :target_evaluation_criteria
  has_many :startup_feedback, dependent: :destroy
  has_many :timeline_event_files, dependent: :destroy
  has_many :timeline_event_grades, dependent: :destroy
  has_many :timeline_event_owners, dependent: :destroy
  has_many :students, through: :timeline_event_owners
  has_one :course, through: :target
  has_many :submission_reports,
           foreign_key: "submission_id",
           inverse_of: :submission,
           dependent: :destroy

  delegate :title, to: :target

  scope :not_auto_verified, -> { joins(:target_evaluation_criteria).distinct }
  scope :auto_verified, -> { where.not(id: not_auto_verified) }
  scope :passed, -> { where.not(passed_at: nil) }
  scope :live, -> { where(archived_at: nil) }
  scope :failed, -> { where(passed_at: nil).where.not(evaluated_at: nil) }
  scope :pending_review, -> { live.not_auto_verified.where(evaluated_at: nil) }
  scope :evaluated_by_faculty, -> { where.not(evaluated_at: nil) }
  scope :from_students,
        ->(students) {
          joins(:timeline_event_owners).where(
            timeline_event_owners: {
              student: students
            }
          )
        }

  CHECKLIST_STATUS_NO_ANSWER = "noAnswer"
  CHECKLIST_STATUS_PASSED = "passed"
  CHECKLIST_STATUS_FAILED = "failed"

  def self.valid_checklist_status
    [
      CHECKLIST_STATUS_NO_ANSWER,
      CHECKLIST_STATUS_PASSED,
      CHECKLIST_STATUS_FAILED
    ].freeze
  end

  # Accessors used by timeline builder form to create TimelineEventFile entries.
  # Should contain a hash: { identifier_key => uploaded_file, ... }
  attr_accessor :files

  def reviewed?
    timeline_event_grades.present?
  end

  def overall_grade_from_score
    return if score.blank?

    { 1 => "good", 2 => "great", 3 => "wow" }[score.floor]
  end

  def student
    students.first
  end

  def passed?
    passed_at.present?
  end

  def team_submission?
    target.team_target?
  end

  def pending_review?
    passed_at.blank? && evaluated_at.blank?
  end

  def status
    if passed_at.blank?
      evaluated_at.present? ? :failed : :pending
    else
      evaluated_at.present? ? :passed : :marked_as_complete
    end
  end

  def archived?
    archived_at.present?
  end

  def live?
    !archived?
  end

  def actions_url
    repo = students.first.github_repository
    "https://github.com/#{repo}/actions" if repo
  end
end

app/controllers/timeline_events_controller.rb
class TimelineEventsController < ApplicationController
  before_action :authenticate_user!

  # GET /submissions/:id/review
  def review
    submission = authorize(TimelineEvent.find(params[:id]))
    @course = submission.target.course
    render html: '', layout: 'app_router'
  end

  # GET /submissions/:id
  def show
    @submission = authorize(TimelineEvent.find(params[:id]))
    render layout: 'student'
  end
end

app/views/timeline_events/_audio.html.erb
<audio class="p-3" controls src="<%= download_timeline_event_file_path(file) %>">

app/views/timeline_events/_files.html.erb
<div class="flex flex-wrap ps-3 ">
  <% files.with_attached_file.each do |timeline_event_file| %>
    <a class="me-3 mt-3 flex border overflow-hidden rounded hover:shadow-md border-red-300 bg-white text-red-600 hover:border-red-500 hover:text-red-600 focus:ring-2 focus:ring-offset-2 focus:ring-focusColor-500" href="<%= download_timeline_event_file_path(timeline_event_file) %>" target="_blank">
      <span class="course-show-attachments__attachment-title rounded text-xs font-semibold inline-block whitespace-nowrap truncate w-32 md:w-42 h-full px-3 py-2 leading-loose"><%= timeline_event_file.file.filename %></span>
      <span class="flex w-10 justify-center items-center p-2 bg-red-600 text-white">
        <i class="if i-download-regular"></i>
      </span>
    </a>
  <% end %>
</div>

app/views/timeline_events/show.html.erb
<% presenter = TimelineEvents::ShowPresenter.new(self, @submission) %>
<% content_for(:head) do %>
  <title><%= presenter.page_title %></title>
<% end %>
<div class="bg-gray-50 md:pt-18">
  <div class="max-w-5xl mx-auto p-4">
    <div class="flex items-center gap-3">
      <div class="bg-blue-100 rounded-full text-blue-500 h-10 w-10 flex items-center justify-center">
        <i class="if i-journal-text-light if-fw text-xl"></i>
      </div>
      <p class="text-md font-semibold"><%= @submission.title %></p>
    </div>
    <div class="flex flex-wrap gap-5 py-5">
      <div class="pe-5 border-e border-gray-300">
        <p class="text-xs text-gray-500"><%= t(".submission_from") %></p>
        <p class="text-sm font-semibold"><%= presenter.submission_from %></p>
      </div>
      <% if presenter.team_name.present? %>
        <div class="pe-5 border-e border-gray-300">
          <p class="text-xs text-gray-500"><%= t(".team") %></p>
          <p class="text-sm font-semibold"><%= presenter.team_name %></p>
        </div>
      <% end %>
      <div class="pe-5 border-e border-gray-300">
        <p class="text-xs text-gray-500"><%= t(".submitted_on") %></p>
        <p class="text-sm font-semibold"> <%= @submission.created_at.strftime("%b %d, %Y")%></p>
      </div>
      <% if @submission.evaluated_at.present? %>
        <div class="pe-5 border-e border-gray-300">
          <p class="text-xs text-gray-500"><%= t(".reviewed_on") %></p>
          <p class="text-sm font-semibold"><%= @submission.evaluated_at.strftime("%b %d, %Y") %></p>
        </div>
      <% end %>
      <div>
        <p class="text-xs text-gray-500"><%= t(".status") %></p>
        <% if @submission.passed_at.present? %>
          <p class="text-sm font-semibold text-green-500"><%= t(".accepted") %></p>
        <% elsif  @submission.evaluated_at.present? %>
          <p class="text-sm font-semibold text-red-500"><%= t(".rejected") %></p>
        <% else %>
          <p class="text-sm font-semibold text-blue-500"><%= t(".pending") %></p>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div class="max-w-5xl mx-auto px-4 mt-4 md:mt-6">
  <div class="flex flex-col bg-gray-50 p-4 rounded-md border border-gray-200 px-5">
    <% @submission.checklist.each do |item| %>
      <div class="flex items-start gap-x-2">
        <div class="mt-2">
          <i class="<%= presenter.icon_class_for(item) %>"></i>
        </div>
        <div>
          <div class="convert-markdown pt-2 text-sm font-semibold" data-json-props="<%= presenter.markdown_prop(item["title"]) %>">
            <%= item["title"] %>
          </div>
          <% if presenter.render_markdown?(item) %>
            <div class="convert-markdown p-1 text-sm" data-json-props="<%= presenter.markdown_prop(item["result"]) %>">
              <%= item["result"] %>
            </div>
          <% elsif presenter.audio?(item) %>
            <%= render "audio", file: presenter.audio_file(item) %>
          <% elsif presenter.files?(item) %>
            <%= render "files", files: presenter.files(item) %>
          <% elsif presenter.link?(item) %>
            <a class="max-w-fc mt-1 me-3 flex border overflow-hidden rounded hover:shadow-md border-blue-400 bg-white text-blue-700 hover:border-blue-600 hover:text-blue-800 focus:ring-2 focus:ring-offset-2 focus:ring-focusColor-500" href="<%= item["result"] %>">
              <span class="rounded text-sm font-semibold inline-block whitespace-nowrap truncate w-32 md:w-42 h-full px-3 py-2">
                <%= item["result"] %>
              </span>
              <span class="flex w-10 justify-center items-center p-2 bg-blue-700 text-white">
                <i class="if i-external-link-light if-fw" ></i>
              </span>
            </a>
          <%  else %>
            <div class="p-3 text-sm"> <%= item["result"].join(" | ")%></div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="flex flex-col py-10">
    <h2 class="font-semibold text-2x"><i class="if i-journal-text-regular if-fw mr-2" ></i><%= t(".feedback", count: @submission.startup_feedback.count) %></h2>
    <% unless @submission.startup_feedback.present? %>
      <p class="pt-2 text-gray-400"><%= t(".no_feedbacks") %></p>
    <% end %>
    <% @submission.startup_feedback.includes(faculty: [user: [avatar_attachment: :blob]]).each do |feedback| %>
      <div class="flex bg-gray-50 p-4 rounded-md mt-2">
        <div class="shrink-0 w-8 h-8 bg-gray-300 rounded-full overflow-hidden me-3 object-cover mt-1">
          <% if feedback.faculty.user.avatar.attached? %>
            <%= image_tag feedback.faculty.user.avatar_url(variant: :thumb) %>
          <% else %>
            <%= image_tag feedback.faculty.user.initials_avatar %>
          <% end %>
        </div>
        <div>
          <h3 class="font-semibold text-base leading-tight block md:inline-flex self-end"><%= feedback.faculty.name %></h3>
          <p class="font-light text-gray-500 text-xs block"><%= feedback.faculty.title %></p>
          <div class="convert-markdown text-sm pt-2" data-json-props="<%= presenter.markdown_prop(feedback.feedback) %>"> <%= feedback.feedback%> </div>
        </div>
      </div>
    <% end %>
  </div>
</div>