config/routes.rb
require 'override_csp'

Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: '/graphiql', graphql_path: '/graphql'
  end

  direct :rails_public_blob do |blob|
    if Rails.env.development? || Rails.env.test? || ENV['CLOUDFRONT_HOST'].blank?
      route =
        if blob.is_a?(ActiveStorage::Variant) || blob.is_a?(ActiveStorage::VariantWithRecord)
          :rails_representation
        else
          :rails_blob
        end
      route_for(route, blob, only_path: true)
    else
      Cloudfront::GenerateSignedUrlService.new(blob).generate_url
    end
  end

  post '/graphql', to: 'graphql#execute'

  devise_for :users, only: %i[sessions omniauth_callbacks], controllers: { sessions: 'users/sessions', omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_scope :user do
    post 'users/send_reset_password_email', controller: 'users/sessions', action: 'send_reset_password_email', as: 'user_send_reset_password_email'
    get 'users/token', controller: 'users/sessions', action: 'token', as: 'user_token'
    get 'users/auth_callback', controller: 'users/sessions', action: 'auth_callback', as: 'user_auth_callback'
    get 'users/reset_password', controller: 'users/sessions', action: 'reset_password', as: 'reset_password'
    post 'users/update_password', controller: 'users/sessions', action: 'update_password', as: 'update_password'
    get 'users/sign_in_with_email', controller: 'users/sessions', action: 'sign_in_with_email', as: 'sign_in_with_email'
    get 'users/request_password_reset', controller: 'users/sessions', action: 'request_password_reset', as: 'request_password_reset'

    if Rails.env.development?
      get 'users/auth/developer', controller: 'users/omniauth_callbacks', action: 'passthru', as: 'user_developer_omniauth_authorize'
      post 'users/auth/developer/callback', controller: 'users/omniauth_callbacks', action: 'developer'
    end
  end

  get 'users/delete_account', controller: 'users', action: 'delete_account', as: 'delete_account'

  post 'users/email_bounce', controller: 'users/postmark_webhook', action: 'email_bounce'

  get 'users/update_email', controller: 'users', action: 'update_email', as: 'update_email'

  authenticate :user, ->(u) { AdminUser.where(email: u.email).present? } do
    mount Delayed::Web::Engine, at: '/jobs'
    mount OverrideCsp.new(Flipper::UI.app(Flipper)), at: '/toggle'
  end

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  resource :applicants, only: [] do
    get '/:token/enroll', action: 'enroll', as: 'enroll'
  end

  resources :notifications, only: %i[show]

  resource :school, only: [] do
    get 'customize'
    get 'admins'
    post 'images'
  end

  namespace :school, module: 'schools' do
    [
      '/',
      'courses',
      'courses/new',
      'courses/:course_id',
      'courses/:course_id/details',
      'courses/:course_id/images',
      'courses/:course_id/actions',
      'courses/:course_id/cohorts',
      'courses/:course_id/cohorts/new',
      'cohorts/:cohort_id/details',
      'cohorts/:cohort_id/actions',
      'courses/:course_id/students',
      'courses/:course_id/students/new',
      'courses/:course_id/students/import',
      'students/:student_id/details',
      'students/:student_id/actions',
      'courses/:course_id/teams',
      'courses/:course_id/teams/new',
      'teams/:team_id/details',
      'teams/:team_id/actions',
    ].each do |path|
      get path, action: 'school_router'
    end

    resources :faculty, only: %i[create update destroy], as: 'coaches', path: 'coaches' do
      collection do
        get '/', action: 'school_index'
      end
    end

    resources :calendars, only: %i[update], controller: 'calendars'
    resources :calendar_events, only: %i[update destroy], controller: 'calendar_events'

    resources :targets, only: [] do
      resource :content_block, only: %i[create]
      member do
        get 'action', action: 'action'
        patch 'update_action', action: 'update_action'
      end
    end

    resources :cohorts, only: [] do
      member do
        post 'bulk_import_students'
      end
    end

    resources :assignments, only: [] do
      member do
        patch :update_milestone_number
      end
    end

    resources :courses, only: [] do
      member do
        get 'applicants'
        get 'calendar_events'
        get 'curriculum'
        get 'exports'
        get 'authors'
        get 'certificates'
        post 'certificates', action: 'create_certificate'
        get 'evaluation_criteria'
        post 'attach_images'
        get 'calendar_month_data'
        get 'assignments'
      end

      resources :calendar_events, only: %i[new create show edit], controller: 'calendar_events'

      resources :calendars, only: %i[new create edit], controller: 'calendars'

      resources :authors, only: %w[show new]

      resources :applicants, only: :show do
        member do
          get 'actions', action: :show
          get 'details', action: :show
        end
      end

      resources :targets, only: [] do
        member do
          get 'content'
          get 'details'
          get 'versions'
        end
      end

      resources :levels, only: %i[create]

      resources :faculty, as: 'coaches', path: 'coaches', only: [] do
        collection do
          get '/', action: 'course_index'
        end
      end

      get 'students'
      post 'delete_coach_enrollment'
      post 'update_coach_enrollments'
    end

    resources :students, as: 'students', path: 'students', except: %i[index] do
      collection do
        post 'team_up'
      end
    end

    resources :levels, only: %i[update] do
      resources :target_groups, only: %i[create]
    end

    resources :target_groups, only: %i[update]

    resources :communities, only: %i[index]
  end

  resources :organisations, only: %i[show index] do
    resources :cohorts, module: 'organisations', only: %i[show] do
      member do
        get 'students'
      end
    end

    resources :courses,  module: 'organisations', only: [] do
      member do
        get 'active_cohorts'
        get 'ended_cohorts'
      end
    end
  end

  namespace :org, module: 'organisations' do
    resources :students, only: %[show] do
      member do
        get 'submissions'
      end
    end
  end

  resources :communities, only: %i[show] do
    member do
      get 'new_topic'
      get ':name', action: 'show'
    end
  end

  get 'topics/:id(/:title)', controller: 'topics', action: 'show', as: 'topic'

  get 'posts/:id/versions', controller: 'posts', action: 'versions', as: 'post_version'

  get 'dashboard', controller: 'users', action: 'dashboard', as: 'dashboard'

  resource :user, only: %i[edit] do
    post 'upload_avatar'
    post 'clear_discord_id'
    get 'discord_account_required'
  end

  resources :timeline_event_files, only: %i[create] do
    member do
      get 'download'
    end
  end

  scope 'coaches', controller: 'faculty' do
    get '/', action: 'index', as: 'coaches_index'
  end

  # Student show
  scope 'students', controller: 'students' do
    get '/:id/report', action: 'report', as: 'student_report'
  end

  get 'styleguide', to: 'home#styleguide', constraints: DevelopmentConstraint.new

  get 'manifest', to: 'home#manifest'
  get 'offline', to: 'home#offline'
  root 'home#index'

  get 'agreements/:agreement_type', as: 'agreement', controller: 'home', action: 'agreement'

  resources :targets, only: %i[show] do
    member do
      get 'details_v2'
      get ':slug', action: 'show'
    end
  end

  resources :timeline_events, only: %i[show], path: 'submissions' do
    member do
      get 'review', action: 'review'
    end
  end

  resources :courses, only: %i[show] do
    member do
      get 'review', action: 'review'
      get 'cohorts', action: 'cohorts'
      get 'calendar', action: 'calendar'
      get 'calendar_month_data', action: 'calendar_month_data'
      get 'leaderboard', action: 'leaderboard'
      get 'curriculum', action: 'curriculum'
      get 'report', action: 'report'
      get 'apply', action: 'apply'
      post 'apply', action: 'process_application'
      get '/(:name)', action: 'show'
    end
  end

  resources :cohorts, only: %i[show] do
    member do
      get 'students', action: 'students'
    end
  end

  resources :markdown_attachments, only: %i[create] do
    member do
      get '/:token', action: 'download', as: 'download'
    end
  end

  get '/c/:serial_number', to: 'issued_certificates#verify', as: :issued_certificate
  get '/help/:document', to: 'help#show'
  get '/oauth/:provider', to: 'home#oauth', as: 'oauth', constraints: SsoConstraint.new
  get '/oauth_error', to: 'home#oauth_error', as: 'oauth_error'

  # Allow developers to simulate the error pages.
  get '/errors/:error_type', to: 'errors#simulate', constraints: DevelopmentConstraint.new

  get '/service-worker.js', to: 'home#service_worker'
  get '/favicon.ico', to: 'home#favicon'
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  include RecaptchaVerifiable
  include DiscordAccountRequirable

  before_action :authenticate_user!,
                except: %i[show apply process_application curriculum]

  before_action :preview_or_authenticate, only: %i[curriculum]
  before_action :require_discord_account, only: %i[curriculum report]

  # GET /courses/:id/curriculum
  def curriculum
    @presenter = Courses::CurriculumPresenter.new(view_context, @course)
    render layout: "student_course"
  end

  # GET /courses/:id/leaderboard?weeks_before=
  def leaderboard
    @course = authorize(find_course)
    @on = params[:on]
    render layout: "student_course"
  end

  # GET /courses/:id/apply
  def apply
    @course = authorize(find_course)
    @show_checkbox_recaptcha = params[:visible_recaptcha].present?

    save_tag
  end

  # POST /courses/:id/apply
  def process_application
    @course = authorize(find_course)

    form = Courses::EnrollmentForm.new(@course)

    recaptcha_success =
      recaptcha_success?(@form, action: "public_course_enrollment")

    unless recaptcha_success
      redirect_to apply_course_path(params[:id], visible_recaptcha: 1)
      return
    end

    if form.validate(params)
      form.create_applicant(session)

      flash[:success] = t(".sent_mail")

      redirect_to root_path
    else
      flash[:error] = t(
        ".errors",
        form_errors: form.errors.full_messages.join(", ")
      )

      redirect_to apply_course_path(params[:id], visible_recaptcha: 1)
    end
  end

  # GET /courses/:id/(:slug)
  def show
    @course = authorize(find_course)
    render layout: "student"
  end

  # GET /courses/:id/review
  def review
    @course = authorize(find_course)
    render html: "", layout: "app_router"
  end

  # GET /courses/:id/cohorts
  def cohorts
    @course = authorize(find_course)
    render layout: "student_course"
  end

  # GET /courses/:id/report
  def report
    @course = authorize(find_course)
    @presenter = Courses::ReportPresenter.new(view_context, @course, student)
    render layout: "student_course"
  end

  # GET /courses/:id/calendar
  def calendar
    @course = authorize(find_course)
    @presenter = Courses::CalendarsPresenter.new(view_context, @course, params)
    render layout: "student_course"
  end

  def calendar_month_data
    @course = authorize(find_course)
    @presenter = Courses::CalendarsPresenter.new(view_context, @course, params)
    render json: @presenter.month_data
  end

  private

  def course
    @course ||= Course.find(params[:id])
  end

  def preview_or_authenticate
    course = find_course

    authenticate_user! unless course.public_preview?

    @course = authorize(course)
  end

  def student
    @student ||=
      @course.students.not_dropped_out.find_by(user_id: current_user.id)
  end

  def find_course
    policy_scope(Course).find(params[:id])
  end

  def save_tag
    return if params[:tag].blank?

    if params[:tag].in?(current_school.student_tag_list)
      session[:applicant_tag] = params[:tag]
    end
  end
end

app/controllers/organisations/courses_controller.rb
module Organisations
  class CoursesController < ApplicationController
    before_action :authenticate_user!
    before_action :find_organisation_and_course,
                  only: %i[active_cohorts ended_cohorts]

    layout "student"

    def active_cohorts
      @active_cohorts = find_cohorts(:active)
    end

    def ended_cohorts
      @ended_cohorts = find_cohorts(:ended)
    end

    private

    def find_organisation_and_course
      @organisation = policy_scope(Organisation).find(params[:organisation_id])
      @course =
        authorize current_school.courses.find(params[:id]),
                  policy_class: Organisations::CoursePolicy
      @cohorts = @organisation.cohorts.where(course_id: @course.id).distinct
    end

    def find_cohorts(status)
      cohorts = status == :active ? @cohorts.active : @cohorts.ended
      paged_cohorts = cohorts.page(params["#{status}_cohort_page"]).per(10)
      if paged_cohorts.count.zero?
        paged_cohorts.page(paged_cohorts.total_pages).per(10)
      else
        paged_cohorts
      end
    end
  end
end

app/views/courses/_event_card.html.erb
  <div class="rounded-xl shadow-sm md:shadow">
    <div
      class="<%="block px-4 pt-4 bg-#{event.color}-100 bg-opacity-75 rounded-t-xl transition focus:outline-none"%>"
      >
      <div class="flex justify-between">
        <div class="flex gap-3 items-start flex-1">
          <div class="<%="w-2 h-2 mt-3 rounded-full " + "bg-#{event.color}-500"%>"></div>
          <div class="w-full">
            <p class="font-semibold text-lg"><%= event.title %></p>
            <p class="w-full font-medium text-sm text-gray-700 pb-2 border-black/5">
              <%= event.display_time %>
            </p>
          </div>
        </div>
      </div>
    </div>

    <% if event.link_url.present? %>
      <div>
        <a
          href=<%= event.link_url %>
          ariaLabel="Link to event"
          target="_blank"
          rel="noopener noreferrer"
          class="<%="ps-9 pe-5  py-2.5 block text-primary-500 font-medium text-sm bg-opacity-75 hover:underline focus:underline focus:outline-none focus:ring-2 focus:ring-focusColor-500 transition " + "bg-#{event.color}-100 hover:bg-#{event.color}-100 focus:bg-#{event.color}-100"%>">
          <div class="flex gap-2 items-center">
            <i class="if i-external-link-regular if-fw rtl:-rotate-90"></i>
            <p>
            <%= event.link_title.present? ? event.link_title : event.link_url %>
            </p>
          </div>
        </a>
      </div>
    <% end %>
    <div class="<%="bg-#{event.color}-50 bg-opacity-75 ps-9 rounded-b-xl pe-5  py-4"%>">
      <div data-re-component="MarkdownBlock" data-re-json="<%= { markdown: event.description }.to_json %>"></div>
    </div>
  </div>

app/views/courses/_topper_avatar.html.erb
<div class="leaderboard__winner-avatar">
  <% if student.avatar.attached? %>
    <%= image_tag (student.avatar_variant(:thumb)), class: 'w-full object-contain' %>
  <% else %>
    <%= image_tag (student.initials_avatar), class: 'w-full object-contain' %>
  <% end %>
</div>

app/views/courses/apply.html.erb
<% presenter = Courses::ApplyPresenter.new(self, @course, @show_checkbox_recaptcha) %>
<% content_for(:head) do %>
  <title><%= presenter.page_title %></title>
<% end %>
<div class="flex min-h-screen bg-gray-50 items-center justify-center">
  <div class="py-8 w-full">
    <div class="container mx-auto px-3 max-w-lg">
      <div
        class="relative flex flex-col shadow-xl rounded-lg overflow-hidden bg-white border"
      >
        <div class="flex flex-col text-gray-900 bg-gray-50 text-white">
          <div class="relative pb-1/2 bg-primary-900">
            <% if presenter.thumbnail_url.present? %>
              <img
                class="absolute h-full w-full object-cover"
                src="<%= presenter.thumbnail_url %>"
              />
            <% else %>
              <div
                class="course-apply__cover-default absolute h-full w-full svg-bg-pattern-1"
              ></div>
            <% end %>
          </div>
        </div>
        <div>
          <div class="p-4 pt-5 md:px-12 md:py-12 md:pt-10">
            <%= form_with( url: apply_course_path(@course), method: :post, class: 'flex flex-col', local: true) do |f| %>
              <h4 class="font-bold">
                <%= t('.heading', course_name: presenter.course_name) %>
              </h4>
              <div class="w-full">
                <div class="mt-4">
                  <label
                    for="email"
                    class="inline-block tracking-wide text-xs font-semibold"
                  >
                    <%= t('.email_label') %>
                  </label>
                  <%= f.email_field :email, value: params[:email], maxlength: 256, placeholder: t('.email_placeholder'), required: true, class: 'appearance-none h-10 mt-1 block w-full border border-gray-300 rounded py-2 px-4 text-sm bg-gray-50 hover:bg-gray-50 focus:outline-none focus:bg-white focus:border-primary-400' %>
                </div>
                <div class="mt-4">
                  <label
                    for="name"
                    class="inline-block tracking-wide text-xs font-semibold"
                  >
                    <%= t('.name_label') %>
                  </label>
                  <%= f.text_field :name, value: params[:name], maxlength: 128, placeholder: t('.name_placeholder'), required: true, class: 'appearance-none h-10 mt-1 block w-full border border-gray-300 rounded py-2 px-4 text-sm bg-gray-50 hover:bg-gray-50 focus:outline-none focus:bg-white focus:border-primary-400' %>
                </div>
                <% if @show_checkbox_recaptcha %>
                  <div class="mt-4">
                    <%=
                      recaptcha_tags(
                        site_key: ENV['RECAPTCHA_V2_SITE_KEY'],
                        nonce: content_security_policy_nonce,
                      )
                    %>
                  </div>
                <% else %>
                  <%=
                    recaptcha_v3(
                      action: 'public_course_enrollment',
                      site_key: ENV['RECAPTCHA_V3_SITE_KEY'],
                      nonce: content_security_policy_nonce,
                    )
                  %>
                <% end %>
              </div>
              <%= f.submit t('.apply_button'), data: { disable: true }, class: "btn btn-primary btn-large text-center w-full mt-6" %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="text-center mt-4 text-gray-600">
        <% if presenter.terms_and_conditions? %>
          <a
            href="/agreements/terms-and-conditions"
            class="text-xs cursor-pointer hover:text-primary-500"
          >
            <%= t('.terms_and_conditions') %>
          </a>
        <% end %>
        <% if presenter.terms_and_conditions? && presenter.privacy_policy? %>
          <span class="px-4 text-gray-500">&vert;</span>
        <% end %>
        <% if presenter.privacy_policy? %>
          <a
            href="/agreements/privacy-policy"
            class="text-xs cursor-pointer hover:text-primary-500"
          >
            <%= t('.privacy_policy') %>
          </a>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/courses/cohorts.html.erb
<% presenter = ::Courses::CohortsPresenter.new(self, @course, params[:status]) %>
<% content_for(:head) do %>
  <title><%= presenter.page_title %></title>
<% end %>
<div class="flex flex-col md:pt-18 pb-20 md:pb-4 md:h-screen overflow-y-auto">
  <section class="bg-gray-50 px-4 border-b border-gray-200">
    <div class="max-w-5xl mx-auto pt-4">
      <div class="flex flex-col sm:flex-row justify-between items-start sm:items-center">
        <div class="mt-4">
          <h3 class="text-lg font-semibold" ><%= @course.name %></h3>
          <p class="text-sm text-gray-500">
            <%= t('.students_enrolled_prefix_html', count: presenter.students.count) %>
            <%= t('.students_enrolled_suffix_html', status: presenter.status, count: presenter.cohorts.count) %>
          </p>
        </div>
      </div>
      <div class="mt-4 md:mt-6 flex gap-4 items-center text-sm">
        <% ['active', 'ended'].each do |status| %>
          <% is_current_page = status == presenter.status %>
          <%= link_to cohorts_course_path(@course, status: status), class: "flex items-center #{'p-2 border-b-2 border-primary-500 text-primary-500 font-medium' if is_current_page || (params[:status].nil? && status == 'active') } #{'font-medium p-2 rounded-t-lg hover:text-primary-500 hover:bg-primary-100 transition' unless is_current_page || (params[:status].nil? && status == 'active') }" do %>
            <span><%= t('.cohorts_subheading', status: status.capitalize) %></span>
          <% end %>
        <% end %>
      </div>
    </div>
  </section>
  <% cohorts = presenter.paged_cohorts %>
  <div class="bg-white flex-1 p-4 md:p-6">
    <div class="max-w-5xl mx-auto rounded-lg">
      <div class="grid grid-cols-1 md:grid-cols-2 gap-5">
        <% cohorts.each do |cohort| %>
          <%= link_to cohort_path(cohort), class: "flex items-center justify-between bg-white rounded-lg border border-gray-200 p-6 shadow hover:bg-primary-50 hover:text-primary-500 hover:border-primary-400" do %>
            <div>
              <span class="inline-block font-medium break-all"><%= cohort.name %></span>
              <% if cohort.ends_at.present? %>
                <div>
                  <span class="text-sm text-gray-500 font-medium" ><%= t(".end_date") %> </span>
                  <span class="font-semibold text-sm"><%= cohort.ends_at.strftime("%B %d, %Y") %></span>
                </div>
              <% end %>
            </div>
            <i class="if i-arrow-right-regular rtl:rotate-180 inline-block text-primary-500" aria-hidden="true"></i>
          <% end %>
        <% end %>
      </div>
      <div class="max-w-6xl mx-auto mt-6 flex items-center justify-center overflow-x-auto pb-3">
        <%= paginate cohorts %>
      </div>
      <% if cohorts.total_pages > 1 %>
        <div class="text-center text-sm italic mt-4">
          <%= t('.pagination_notice', page_start: kaminari_page_start(cohorts), page_end: kaminari_page_end(cohorts), count: cohorts.total_count, status: presenter.status)  %>
        </div>
      <% end %>
      <% if cohorts.empty? %>
        <div class="text-center text-sm italic mt-4"><%= t('.nothing_to_show', status: presenter.status ) %></div>
      <% end %>
    </div>
  </div>
</div>

app/views/courses/curriculum.html.erb
<% content_for(:head) do %>
  <title><%= @presenter.page_title %></title>
  <%= vite_stylesheet_tag 'curriculum_overlay', media: 'print' %>
<% end %>
<% content_for(:inner_wrapper) do %>
  <script id="react-root-data" type="application/json">
    <%= @presenter.props_to_json.html_safe %>
  </script>
  <div id="react-root"></div>
<% end %>

app/views/courses/report.html.erb
<% content_for(:head) do %>
  <title><%= @presenter.page_title %></title>
<% end %>
<% content_for(:inner_wrapper) do %>
  <script id="course-student-report__props" type="application/json">
    <%= @presenter.props_to_json.html_safe %>
  </script>
  <div id="react-root"></div>
<% end %>

app/views/courses/show.html.erb
<% presenter = Courses::ShowPresenter.new(self, @course) %>
<% content_for(:head) do %>
  <title><%= presenter.page_title %></title>
<% end %>
<div class="pb-8 bg-gray-50 ">
  <div class="relative md:pt-18 bg-primary-900">
    <div class="relative pb-1/2 md:pb-1/4 2xl:pb-1/5">
      <% if presenter.cover_image.present? %>
        <img
          class="absolute h-full w-full object-cover"
          src="<%= presenter.cover_image %>"
        />
      <% else %>
        <div
          class="course-show__cover-default absolute h-full w-full svg-bg-pattern-1"
        ></div>
      <% end %>
    </div>
  </div>
  <div class="px-3">
    <div class="flex flex-col md:flex-row lg:max-w-5xl mx-auto">
      <div class="flex-1">
        <div
          class="course-show__header-cta-container bg-white border-transparent shadow rounded-lg -mt-5 md:-mt-7 z-10 relative pt-4 pb-5 md:py-8"
        >
          <div class="flex md:flex-row flex-col">
            <div class="px-4 md:px-8 w-full">
              <h1 class="font-bold leading-snug">
                <%= @course.name %>
              </h1>
              <div class="mt-2">
                <%= @course.description %>
              </div>
            </div>
            <% if @course.public_preview? && @course.highlights.empty? %>
              <div
                class="w-full md:w-1/3 flex justify-center items-center mt-4 md:mt-0 px-4 md:px-8"
              >
                <a
                  href="<%= curriculum_course_path(@course) %>"
                  class="btn btn-primary btn-large w-full"
                >
                  <%= presenter.user_is_student? ? t('.continue_course') : t('.preview_course') %>
                </a>
              </div>
            <% end %>
            <% if @course.public_signup && @course.highlights.empty? %>
              <div
                class="w-full md:w-1/3 flex justify-center items-center mt-4 md:mt-0 px-4 md:px-8"
              >
                <a
                  href="<%= apply_course_path(@course) %>"
                  class="btn btn-success btn-large w-full"
                >
                  <%= t('.apply_now') %>
                </a>
              </div>
            <% end %>
          </div>
        </div>
        <div class="mt-4">
          <% if presenter.show_about? %>
            <div class="max-w-3xl mx-auto relative z-10 pb-6 md:pb-8">
              <div
                class="px-4 md:px-8 markdown-block markdown-block__permissive"
              >
                <div data-json-props="<%= presenter.markdown_prop(presenter.about) %>" class="convert-markdown">
                  <%= presenter.about %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
      <% if @course.highlights.present? %>
        <div class="md:ms-4 md:w-1/3 flex flex-col justify-between">
          <div
            class="py-4 md:py-6 bg-white border-transparent shadow rounded-lg md:-mt-7 z-10 relative md:sticky md:top-0"
          >
            <div class="space-y-6 px-4 md:px-6">
              <% @course.highlights.map do |highlight| %>
                <div class="flex">
                  <div class="w-12">
                    <div
                      class="flex items-center justify-center h-10 w-10 shadow bg-primary-100 text-primary-400 rounded-full p-2"
                    >
                      <i class="<%="if text-lg i-#{highlight['icon']}"%>"></i>
                    </div>
                  </div>
                  <div class="ms-2">
                    <div class="text-sm font-bold">
                      <%= highlight['title']%>
                    </div>
                    <div class="text-xs">
                      <%= highlight['description']%>
                    </div>
                  </div>
                </div>
              <%end%>
            </div>
            <% if @course.public_preview? %>
              <div class="p-4 pb-0 md:p-6 md:pb-0">
                <a
                  href="<%= curriculum_course_path(@course) %>"
                  class="btn btn-primary btn-large w-full"
                >
                  <%= presenter.user_is_student? ? t('.continue_course') : t('.preview_course') %>
                </a>
              </div>
            <% end %>
            <% if @course.public_signup %>
              <div class="p-4 pb-0 md:p-6 md:pb-0">
                <a
                  href="<%= apply_course_path(@course) %>"
                  class="btn btn-success btn-large w-full"
                >
                  <%= t('.apply_now') %>
                </a>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
    <div class="hidden md:block max-w-5xl mx-auto">
      <% if @course.public_signup %>
        <div
          class="course-show__footer-cta-container bg-white py-12 px-4 text-center mt-8 border-transparent shadow rounded-lg"
        >
          <h2 class="text-3xl leading-tight">
            <span class="font-normal"> <%= t(".enroll") %> </span>
            <span class="block font-bold">
              <%= @course.name %>
            </span>
          </h2>
          <a
            href="<%= apply_course_path(@course) %>"
            class="btn btn-large btn-success w-full sm:w-auto course-show__footer-cta-button shadow mt-3"
            ><%= t('.apply_now') %></a
          >
        </div>
      <% end %>
    </div>
  </div>
</div>